# Generated by Django 5.0.3 on 2024-04-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="agendamentos",
        ),
    ]
