# Generated by Django 5.0.1 on 2024-04-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingresso",
            name="data_reserva",
        ),
        migrations.RemoveField(
            model_name="ingresso",
            name="forma_de_pagamento",
        ),
        migrations.RemoveField(
            model_name="ingresso",
            name="local",
        ),
        migrations.RemoveField(
            model_name="ingresso",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="ingresso",
            name="usuario",
        ),
        migrations.AddField(
            model_name="ingresso",
            name="letra",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ingresso",
            name="localizacao",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ingresso",
            name="numero",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ingresso",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ingresso",
            name="tipo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
